In [58]:
#导入torch包
import torch
import numpy

In [3]:
x = torch.arange(10)
x#生成一个数值组成的数组

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
x.shape

torch.Size([10])

In [9]:
x.numel()

10

In [10]:
X = x.reshape(2,5)
X #x是张量，改变张量的形状而不改变元素数量和元素值

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [12]:
#全零
torch.zeros((2,5,5))

#(个数，维度）？

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [18]:
#全一
torch.ones(2,5,5)

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]])

In [19]:
torch.randn(3,4)

tensor([[ 0.9741, -1.5873, -0.7288,  0.3922],
        [-0.5216,  1.1752, -0.4743, -0.0169],
        [-0.6210, -0.0269,  0.4699, -1.0408]])

In [20]:
#确定张量的值
torch.tensor([[1,2],[3,4],[5,6]])

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [23]:
x1 = torch.tensor([[1,2],[3,4]])
x2 = torch.tensor([[1,2],[3,4]])
x1+x2,x1-x2,x1*x2,x1/x2,x1 ** x2
#基础四则运算

(tensor([[2, 4],
         [6, 8]]),
 tensor([[0, 0],
         [0, 0]]),
 tensor([[ 1,  4],
         [ 9, 16]]),
 tensor([[1., 1.],
         [1., 1.]]),
 tensor([[  1,   4],
         [ 27, 256]]))

In [24]:
#拼接张量
X =  torch.arange(12,dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [26]:
X == Y
X.sum()#求和以及逻辑运算符

tensor(66.)

In [28]:
#广播机制执行元素操作
a = torch.arange(3).reshape((3,1))
b = torch.arange(2).reshape((1,2))
a,b,a+b#对应行进行相加，全部求和

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]),
 tensor([[0, 1],
         [1, 2],
         [2, 3]]))

In [30]:
X[-1],a[1:3]#掐头不去尾

(tensor([ 8.,  9., 10., 11.]),
 tensor([[1],
         [2]]))

In [48]:
b = torch.arange(12).reshape((3,4))
b[0,1] = 8
b

tensor([[ 0,  8,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [49]:
b[0:2,:] = 0
b

tensor([[ 0,  0,  0,  0],
        [ 0,  0,  0,  0],
        [ 8,  9, 10, 11]])

In [53]:
before = id(Y)
Y = Y + X
 #会为新结果重新分配内存
before,id(Y),id(Y) == before

(2278109449648, 2278109448208, False)

In [57]:
before = id(X)
X += Y
id(X),before,id(X) == before


(2278165626608, 2278165626608, True)

In [60]:
#转换为numpy张量
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)


(numpy.ndarray, torch.Tensor)

In [61]:
# data_pretreatment

In [64]:
import os

In [70]:
os.mkdir(os.path.join('..','data'))
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n')
    f.write('NA,Pave,127500\n')
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')


FileExistsError: [WinError 183] 当文件已存在时，无法创建该文件。: '..\\data'

In [71]:
import pandas as pd

data = pd.read_csv(data_file)
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [73]:
input ,output = data.iloc[:,0:2],data.iloc[:,2]
input = input.fillna(input.mean())
input#缺失值处理

F:\.temp\ipykernel_8752\93689339.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  input = input.fillna(input.mean())


NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

In [74]:
input = pd.get_dummies(input,dummy_na=True)
input

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [76]:
X, y = torch.tensor(input.values),torch.tensor(output.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))