In [2]:
import torch
x = torch.tensor([2, 3, 4], dtype=torch.float, requires_grad=True)
print(x)
y = x * 2
while y.norm() < 1000:
    y = y * 2
print(y)
y.backward(torch.ones_like(y))
print(x.grad)


tensor([2., 3., 4.], requires_grad=True)
tensor([ 512.,  768., 1024.], grad_fn=<MulBackward0>)
tensor([256., 256., 256.])


In [27]:

x = torch.tensor([2,2],dtype=torch.float32,requires_grad=True)

#Case 1
y = x * x
y.sum().backward()
y,x.grad
#Case 2


(tensor([4., 4.], grad_fn=<MulBackward0>), tensor([4., 4.]))

In [26]:
x.grad.zero_()
y1 = torch.dot(x,x)
y1.backward()
y1,x.grad

(tensor(8., grad_fn=<DotBackward0>), tensor([4., 4.]))