In [7]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [8]:
x.requires_grad_(True)
x.grad

In [9]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [10]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [12]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [14]:
x.grad.zero_()
y =  x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [20]:
x.grad.zero_()
y = x*x
u = y.detach()
z = u * x
z.sum().backward()
x.grad 


tensor([0., 1., 4., 9.])